version: '3.1'

services:
  delivery_db:
    image: mysql:8.0.23
    restart: always
    container_name: mysql_bd
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      # - MYSQL_DATABASE=delivery-app-dev
    ports:
      - 3306:3306
